name: Build & Release .NET 10

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{matrix.displayName}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        include:
          - runtime: win-x64
            displayName: Windows-x64
            os: windows-latest
          - runtime: linux-x64
            displayName: Linux-x64
            os: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v5.1.0
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Clean
        run: dotnet clean

      - name: Publish
        shell: bash
        run: |
          dotnet publish S7Patcher.csproj \
            -c Release \
            -r ${{matrix.runtime}} \
            -p:SelfContained=true \
            -p:PublishSingleFile=true \
            -p:StripSymbols=true \
            -o ./publish/${{matrix.runtime}}

      - name: Compress publish output (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          $src = "publish/${{matrix.runtime}}"
          $dst = "${{matrix.displayName}}.zip"
          Compress-Archive -Path "$src\*" -DestinationPath $dst -CompressionLevel Optimal

      - name: Compress publish output (Unix)
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          cd publish/${{matrix.runtime}}
          zip -9 -r ../../${{matrix.displayName}}.zip .

      - name: Upload compressed artifact
        uses: actions/upload-artifact@v6
        with:
          name: dotnet-${{matrix.displayName}}
          path: ${{matrix.displayName}}.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          path: ./artifacts

      - name: Extract version name
        id: get_version
        run: echo "version_name=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release (Draft)
        uses: softprops/action-gh-release@v2.5.0
        with:
          name: ${{steps.get_version.outputs.version_name}}
          tag_name: ${{github.ref_name}}
          body: "Latest Release."
          draft: true
          prerelease: false
          files: |
            ./artifacts/dotnet-Windows-x64/Windows-x64.zip
            ./artifacts/dotnet-Linux-x64/Linux-x64.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
